### ISSUE TITLE
Re complile fail mentioning "ps_d" when using --gitignore

### ISSUE THREAD

**Issue by tolomea** [hakancelikdev/unimport#240]
We've recently started getting the below failure. 
```
Traceback (most recent call last):
  File "/home/gordon/.cache/pre-commit/repotvgski9p/py_env-python3/bin/unimport", line 8, in <module>
    sys.exit(main())
  File "/home/gordon/.cache/pre-commit/repotvgski9p/py_env-python3/lib/python3.10/site-packages/unimport/main.py", line 26, in main
    for path in config.get_paths():
  File "/home/gordon/.cache/pre-commit/repotvgski9p/py_env-python3/lib/python3.10/site-packages/unimport/config.py", line 72, in get_paths
    yield from utils.list_paths(
  File "/home/gordon/.cache/pre-commit/repotvgski9p/py_env-python3/lib/python3.10/site-packages/unimport/utils.py", line 117, in list_paths
    include_regex, exclude_regex = re.compile(include), re.compile(exclude)
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 950, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 836, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.10/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 833, in _parse
    raise source.error(err.msg, len(name) + 1) from None
re.error: redefinition of group name 'ps_d' as group 2; was group 1 at position 72
```
We're running with py3.10.4, and this bit of precommit
```
-   repo: https://github.com/hakancelik96/unimport
    rev: 0.11.1
    hooks:
    -   id: unimport
        args: [--remove, --include-star-import, --ignore-init, --gitignore]
```
It looks like this was caused by our use of --gitignore and the recent (10 hours ago at the time of writing) release of pathspec 0.10.0.

Digging into it I'm seeing that it's taken every line from our .gitignore and wrapped it, so `/prof` has become `^prof(?:(?P<ps_d>/).*)?$` that seems to come from GitWildMatchPattern

**Comment by tolomea** [comment]
for now we are working around it like this
```
-   repo: https://github.com/hakancelik96/unimport
    rev: 0.11.1
    hooks:
    -   id: unimport
        args: [--remove, --include-star-import, --ignore-init, --gitignore]
        additional_dependencies: ["pathspec==0.9.0"]
```

**Comment by hakancelikdev** [comment]
Thank you for opening the Issue I did a few tests, and I solved the problem, but I can't decide yet, the gitignore flag works more correctly in pathspec 0.10.0 and later,

Should I continue to support all versions 0.5.0 and above, or should I support versions 0.10.0 and above?

My idea is to support 0.10.0  and above versions because as I said, unimport will work more correctly if it uses these versions.

**Comment by hakancelikdev** [comment]
Does anyone want to share their opinion?

**Comment by hakancelikdev** [comment]
It seems that Pathspec has stopped supporting Python 3.6, I can only use the 0.10.0 version and above for Python 3.7 and above.

**Comment by tolomea** [comment]
3.6 is no longer maintained https://endoflife.date/python

**Comment by hakancelikdev** [comment]
Yes, I know but I want to support it as much as possible.

**Comment by hakancelikdev** [comment]
It seems unnecessary effort to support 3.6 and windows. https://pypistats.org/packages/unimport

**Comment by hakancelikdev** [comment]
@tolomea can you try version 0.11.2?

**Comment by tolomea** [comment]
I get a new error for 0.11.2

```
Traceback (most recent call last):
  File
"/home/gordon/.cache/pre-commit/repo06pg8pft/py_env-python3/bin/unimport",
line 5, in <module>
    from unimport.__main__ import main
ImportError: cannot import name 'main' from 'unimport.__main__'
(/home/gordon/.cache/pre-commit/repo06pg8pft/py_env-python3/lib/python3.10/site-packages/unimport/__main__.py)
```

**Comment by hakancelikdev** [comment]
Yes, I noticed and fixed this bug right away, can you try version 0.11.3? @tolomea
